apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: frontend-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-webapp
  template:
    metadata:
      labels:
        app: frontend-webapp
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: my-configmap
      containers:
        - name: frontend-webapp
          image: 'faizanmomin2508/cloudethix_configmap_faizan:v2'
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/
              readOnly: true
          ports:
            - containerPort: 80

